### ISSUE TITLE
Unhandled exception when adding item to list.

### ISSUE THREAD

**Issue by mclean25** [BendixMa/implicitly_animated_reorderable_list#1]
I'm getting a weird exception when trying to add an item to the list. I'm not sure why, but it just freezes the app and nothing shows up in the debug console. It first throws an exception in the `isolate_patch.dart`, but if you continue the debugger a couple times you end up at the `implicitly_animated_list_base._calcDiffs()`. Hard to provide more data on this but screenshots provided below:

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/7105182/75099382-edf4cf00-5575-11ea-8cf5-7be6be87d094.png">

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/7105182/75099448-a884d180-5576-11ea-9d0b-26ed40afb367.png">

### List
```.dart
class _TodoListViewState extends State<TodoListView> {
  List<EditableListItem> listItems = [];

  bool _itemIsEditable = false;

  void _goToSortListScreen(BuildContext context) async {
    ListSorter optionsListState =
        new ListSorter(listObject: this.widget.listObject);
    await Navigator.pushReplacement(
        context,
        new MaterialPageRoute(
            builder: (context) => new ChangeNotifierProvider.value(
                value: optionsListState, child: ListSortMainScreen())));
  }

  void _onAddItemEditDone(TextEditingController controller) {
    print('got add item event');
    if (controller.text?.isEmpty ?? true) {
      this.setState(() {
        this.listItems.removeLast();
        print('remove lost');
        this._itemIsEditable = !this._itemIsEditable;
      });
    } else {
      print('Add item submitted with value ${controller.text}');
      DateTime createdTime = DateTime.now().toUtc();
      ListItem newListItem = new ListItem(
          completed: false,
          createdAt: createdTime,
          modifiedAt: createdTime,
          text: controller.text);

      this.widget.listObject.addListItem(
          user: Provider.of<FirebaseUser>(context), listItem: newListItem);

      this.setState(() {
        this.listItems.removeLast();
        this.listItems.add(
          new EditableListItem(
            isEditable: false,
            onEditCompleteCallback: null,
            listItem: newListItem,
          ));
        this._itemIsEditable = !this._itemIsEditable;
      });

      this._addNewEditItem();
    }
  }

  void _addNewEditItem() {
    this.setState(() {
      var k =
        EditableListItem(
          isEditable: true,
          onEditCompleteCallback: this._onAddItemEditDone,
          listItem: new ListItem(
            completed: false,
            createdAt: DateTime.now().toUtc(),
            modifiedAt: DateTime.now().toUtc(),
            text: "default"
          ),
      );

      this.listItems.add(k);
      this._itemIsEditable = !this._itemIsEditable;
    });
  }

  void _onReorderFinished(List<EditableListItem> newItems) {
    setState(() {
      this.listItems
        ..clear()
        ..addAll(newItems);
    });
  }

  Widget _buildReorderableList() {
    // Most of this code is just copied from https://github.com/BendixMa/implicitly_animated_reorderable_list
    // while we get a working example going.
    return ImplicitlyAnimatedReorderableList(
      items: this.listItems,
      shrinkWrap: true,
      areItemsTheSame: (oldItem, newItem) => oldItem.text == newItem.text,
      onReorderFinished: (movedItem, from, to, newItems) => _onReorderFinished(newItems),
      itemBuilder: (context, itemAnimation, listItem, index) {
        return Reorderable(
          key: ValueKey(listItem.listItem),
          builder: (context, dragAnimation, inDrag) {
            final t = dragAnimation.value;
            // If the item is in drag, only return the tile as the
            // SizeFadeTransition would clip the shadow.
            if (t > 0.0) {
              return listItem;
            }
            return SizeFadeTranstion(
              sizeFraction: 0.7,
              curve: Curves.easeInOut,
              animation: itemAnimation,
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: <Widget>[
                  _buildTile(listItem),
                  Divider(height: 0,)
                ],
              )
            );
          }
        );
      },
      updateItemBuilder: (context, itemAnimation, listItem) {
        return Reorderable(
          key: ValueKey(listItem),
          builder: (context, dragAnimation, inDrag) {
            return FadeTransition(
              opacity: itemAnimation,
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: <Widget>[
                  _buildTile(listItem),
                  Divider(height: 0,)
                ],
              ),
            );
          }
        );
      },
    );
  }

  Widget _buildTile(EditableListItem listItem) {
    final theme = Theme.of(context);
    final textTheme = theme.textTheme;

    final List<Widget> actions =
    [
      SlideAction(
        closeOnTap: true,
        color: Colors.redAccent,
        onTap: () {
          // TODO
          setState(
            () => null// selectedLanguages.remove(lang),
          );
        },
        child: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              Icon(
                Icons.delete,
                color: Colors.white,
              ),
              SizedBox(height: 4),
              Text(
                'Delete',
                style: textTheme.body1.copyWith(
                  color: Colors.white,
                ),
              ),
            ],
          ),
        ),
      ),
    ];

    return Slidable(
      actionPane: SlidableBehindActionPane(),
      actions: actions,
      secondaryActions: actions,
      child: new ListItemListView(
        listItem: listItem,
        listObject: this.widget.listObject,
      ),
    );
  }

  @override
  void initState() {
    this
      .widget
      .listObject
      .items
      .forEach((listItem) => listItems.add(
        EditableListItem(
          onEditCompleteCallback: null,
          isEditable: false,
          listItem: listItem,
      )));
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return BaseScaffold(
        title: this.widget.listObject.title,
        floatingActionButton: FloatingActionButton(
          onPressed: () => this._addNewEditItem(),
        ),
        body: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.start,
            children: <Widget>[
              Padding(
                padding: const EdgeInsets.all(8.0),
                child: Container(
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.end,
                    children: <Widget>[
                      RaisedButton(
                        color: Colors.white,
                        child: Text("Prioritize"),
                        onPressed: () => _goToSortListScreen(context),
                        elevation: 0,
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(5),
                          side: BorderSide(color: Colors.grey[300]),
                        )
                      ),
                    ],
                  ),
                ),
              ),
              Flexible(
                fit: FlexFit.loose,
                child: Container(
                  child: _buildReorderableList(),
                ),
              )
            ],
          ),
        ));
  }
}
```

### ```EditableListItem```
```.dart
class EditableListItem
{
  bool isEditable;
  Function onEditCompleteCallback;
  ListItem listItem;

  EditableListItem({
    @required this.isEditable,
    @required this.onEditCompleteCallback,
    @required this.listItem,
  });

  @override
  bool operator ==(Object o) {
    if (identical(this, o)) return true;

    return o is EditableListItem && o.listItem.createdAt == this.listItem.createdAt;
  }

  @override
  int get hashCode => listItem.text.hashCode ^ listItem.createdAt.hashCode;
}
```

Any idea what's going on here? Any ides of what I could provide (other than the source code itself) to try and debug?

**Comment by mclean25** [comment]
Got a better stack tract using `flutter run -v`:

```
[+1645 ms] [DEVICE LOG] 2020-02-22 13:31:47.604336-0800  localhost Runner[83935]: (Flutter) [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Invalid argument(s): Illegal
argument in isolate message : (object is a closure - Function '_onAddItemEditDone@567358528':.)
[        ] [DEVICE LOG] #0      Isolate._spawnFunction (dart:isolate-patch/isolate_patch.dart:551:55)
[        ] [DEVICE LOG] #1      Isolate.spawn (dart:isolate-patch/isolate_patch.dart:391:7)
[        ] [DEVICE LOG] #2      compute (package:flutter/src/foundation/_isolates_io.dart:23:41)
[        ] [DEVICE LOG] #3      DiffUtil.calculateDiff (package:implicitly_animated_reorderable_list/src/diff/myers_diff.dart:17:19)
[        ] [DEVICE LOG] #4      ImplicitlyAnimatedListBaseState._calcDiffs (package:implicitly_animated_reorderable_list/src/implicitly_animated_list_base.dart:158:18)
[        ] [DEVICE LOG] <asynchronous suspension>
[        ] [DEVICE LOG] #5      ImplicitlyAnimatedListBaseState.didUpdateWidget (package:implicitly_animated_reorderable_list/src/implicitly_animated_list_base.dart:149:5)
[        ] [DEVICE LOG] #6      StatefulElement.update (package:flutter/src/widgets/framework.dart:4396:58)
[        ] [DEVICE LOG] #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
[        ] [DEVICE LOG] #8      ComponentElement<…>
[   +4 ms] [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message : (object is a closure - Function
'_onAddItemEditDone@567358528':.)
[        ] #0      Isolate._spawnFunction (dart:isolate-patch/isolate_patch.dart:551:55)
[        ] #1      Isolate.spawn (dart:isolate-patch/isolate_patch.dart:391:7)
[        ] #2      compute (package:flutter/src/foundation/_isolates_io.dart:23:41)
[        ] #3      DiffUtil.calculateDiff (package:implicitly_animated_reorderable_list/src/diff/myers_diff.dart:17:19)
[        ] #4      ImplicitlyAnimatedListBaseState._calcDiffs (package:implicitly_animated_reorderable_list/src/implicitly_animated_list_base.dart:158:18)
[        ] <asynchronous suspension>
[        ] #5      ImplicitlyAnimatedListBaseState.didUpdateWidget (package:implicitly_animated_reorderable_list/src/implicitly_animated_list_base.dart:149:5)
[        ] #6      StatefulElement.update (package:flutter/src/widgets/framework.dart:4396:58)
[   +3 ms] #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
[        ] #8      ComponentElement<…>
```

**Comment by BendixMa** [comment]
The list uses a diff algorithm to calculate the changes and for performance reason it is calculated on a different isolate. As the exception says  
```
Illegal argument in isolate message : (object is a closure - Function
'_onAddItemEditDone@567358528':.)
```   
you're object `EditableListItem` contains a closure (you keep a reference to a function - `_onAddItemEditDone` - outside of its scope) which is not allowed. Why does `EditableListItem` needs to have access to `_onAddItemEditDone` anyway? Usually you should only mutate the state from within the state itself and not pass (especially private methods) around.

In version `0.1.7` I added the `spawnIsolate` field to `ImplicitlyAnimatedList`, so you could try and set it to `false` if `EditableListItem` really really needs to have access to `_onAddItemEditDone`. Note that then everything is calculated on the main thread which could lead to bad performance for long lists.

**Comment by mclean25** [comment]
Ah I see, I didn't know what a "closure" was so that makes much more sense now. Thanks for that.

The idea for having the reference to the function is so that the item in the list can communicate to the list when it's been done editing, so that it can tell the list to submit the new value. As for it being private, that's just an artifact of me moving things around trying to get things to work. I'm not sure how else to let the parent list know when the individual item has finished completing.

Thanks for the explanation and help. It does work once removing that reference. Now just to figure out how to implement what I need without setting `spawnIsolate = false`.

**Comment by BendixMa** [comment]
This is exactly what state management solutions like Provider or Bloc are for. I suggest you to take a look at those and learn how they work. This will allow you to build much more complex apps in the future. 

Alternatively you could inherit the state from a child by adding this to `TodoListViewState`:
```dart
static TodoListViewState of(BuildContext context) {
    return context.findAncestorStateOfType<TodoListViewState>();
  }
```
and then call it like so:
```dart
TodoListViewState.of(context).onAddItemEditDone(text);
```

**Comment by mclean25** [comment]
That makes perfect sense, I don't know why I didn't think to use Provider in this scenario 🤦‍♂. Thanks for your help and the awesome package, I've got things set up much nicer now.
